# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: bb562fef3143005cc87c62e233981147e40f252e92d02b39fb87a32165057f972e698f3da81d165be10794b4af286b254fdd98f2f0e5a95cb244eabc8879b864

test:
  secret_key_base: 2422b06997c91b8b95ab03f115afb619e0c0bcb1ddbf473c69c1626d0c372b5cf38de95473bfb24136d595eb5a50777d157821eed41d3823c9b07dc7384ad930

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
